.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoinlimitededition_qt test_bitcoinlimitededition_qt
clean: FORCE
	$(MAKE) -C .. bitcoinlimitededition_qt_clean test_bitcoinlimitededition_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoinlimitededition_qt_check
bitcoinlimitededition-qt bitcoinlimitededition-qt.exe: FORCE
	 $(MAKE) -C .. bitcoinlimitededition_qt
